export const INCREMENT = 'LONG_PREFIX_INCREMENT' as 'LONG_PREFIX_INCREMENT';
export const DECREMENT = 'LONG_PREFIX_DECREMENT' as 'LONG_PREFIX_DECREMENT';
export const SET_COUNT = 'LONG_PREFIX_SET_COUNT' as 'LONG_PREFIX_SET_COUNT';
